# Generated by Django 4.0 on 2022-01-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_book_created_date_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ManyToManyField(to='home.Book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='home.user'),
        ),
    ]
