# Generated by Django 4.0 on 2022-01-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_order_book_alter_order_ordered_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='book',
            new_name='orderrd_book',
        ),
    ]
