# Generated by Django 4.0 on 2022-01-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_book_order_orderrd_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderrd_book',
            new_name='ordered_book',
        ),
    ]
