# Generated by Django 4.0 on 2022-01-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_orderrd_book_order_ordered_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_book',
            new_name='book',
        ),
    ]
